### ISSUE TITLE
app crashes when we drop a clip that goes to the end

### ISSUE THREAD

**Issue by lawliet7** [lawliet7/goddo-editor#22]
on preview window, if we select in but no out and drop it on the timeline, it will crash.

**stacktrace:**
```
/Users/atetelman/workspace/project/index.js:70
    throw new Error('blah');
          ^
Error: blah
    at Object.<anonymous> (/Users/atetelman/workspace/project/src/index.js:70:11)
    at next (native)
    at step (/Users/atetelman/workspace/project/index-dist.js:246:191)
    at /Users/atetelman/workspace/project/index-dist.js:246:361
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Comment by lawliet7** [comment]
fixed in develop branch
