### ISSUE TITLE
app crashes if we save with no source video

### ISSUE THREAD

**Issue by lawliet7** [lawliet7/goddo-editor#50]
```
Namespace(log_level=None)
Traceback (most recent call last):
  File "...\PycharmProjects\goddo-editor\goddo_player\app\monarch.py", line 253, in __on_save_file
    self.state.preview_window.current_frame_no = self.preview_window.preview_widget.get_cur_frame_no()
  File "...\PycharmProjects\goddo-editor\goddo_player\preview_widget.py", line 39, in get_cur_frame_no
    return int(self.cap.get(cv2.CAP_PROP_POS_FRAMES))
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by lawliet7** [comment]
seems to be fixed, might have missed mentioning in commit
